##  Database  ##
spring:
  datasource:
    url: jdbc:postgresql://dpg-clp4capoh6hc73bsokkg-a/remo
    username: remo
    password: HbBAs8cjJoPeqStbYAKj3BeoKVjcCsPV
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days