##  Database  ##
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/remo
    username: remo
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
  security:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8090/auth/realms/remo
            jwk-set-uri: ${spring.security.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#        client:
#          registration:
#            keycloak:
#              realm: remo
#              client-id: remo
#              authorization-grant-type: authorization_code
#              scope: openid,offline_access,profile
##              client-secret: PEjwGKT58fqbNs5gSS0PUj93MV4B0xq8
#          provider:
#            keycloak:
#              issuer-uri: http://localhost:8090/auth/realms/remo
#              user-name-attribute: preferred_username